/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.learningswing;

/**
 *
 * @author Mirai
 */
public class bai1prac12 extends javax.swing.JFrame {

    /**
     * Creates new form bai1prac12
     */
    public bai1prac12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        num1Input = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        num2Input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        subsButton = new javax.swing.JButton();
        multiButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        resultField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        label1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label1.setText("Num 1:");

        label2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label2.setText("Num 2:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Result:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        subsButton.setText("Substraction");
        subsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsButtonActionPerformed(evt);
            }
        });

        multiButton.setText("Multiple");
        multiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiButtonActionPerformed(evt);
            }
        });

        divideButton.setText("Divide");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subsButton)
                        .addGap(18, 18, 18)
                        .addComponent(multiButton)
                        .addGap(18, 18, 18)
                        .addComponent(divideButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1)
                            .addComponent(jLabel3)
                            .addComponent(label2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num2Input, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(num1Input, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(resultField))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(num1Input))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(num2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(subsButton)
                    .addComponent(multiButton)
                    .addComponent(divideButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
        String num1 = num1Input.getText();
        String num2 = num2Input.getText();
        double number1 = Double.parseDouble(num1);
        double number2 = Double.parseDouble(num2);
        resultField.setText(String.valueOf((number1 + number2)));
    }// GEN-LAST:event_addButtonActionPerformed

    private void subsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_subsButtonActionPerformed
        String num1 = num1Input.getText();
        String num2 = num2Input.getText();
        double number1 = Double.parseDouble(num1);
        double number2 = Double.parseDouble(num2);
        resultField.setText(String.valueOf((number1 - number2)));

    }// GEN-LAST:event_subsButtonActionPerformed

    private void multiButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_multiButtonActionPerformed
        String num1 = num1Input.getText();
        String num2 = num2Input.getText();
        double number1 = Double.parseDouble(num1);
        double number2 = Double.parseDouble(num2);
        resultField.setText(String.valueOf((number1 * number2)));

    }// GEN-LAST:event_multiButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_divideButtonActionPerformed
        String num1 = num1Input.getText();
        String num2 = num2Input.getText();
        double number1 = Double.parseDouble(num1);
        double number2 = Double.parseDouble(num2);
        if (Double.isInfinite(number1 / number2)) {
            resultField.setText("Cannot Divide by Zero!");
        } else {
            resultField.setText(String.valueOf(number1 / number2));
        }
    }// GEN-LAST:event_divideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai1prac12.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai1prac12.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai1prac12.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai1prac12.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai1prac12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton multiButton;
    private javax.swing.JTextField num1Input;
    private javax.swing.JTextField num2Input;
    private javax.swing.JFormattedTextField resultField;
    private javax.swing.JButton subsButton;
    // End of variables declaration//GEN-END:variables
}
