package src.learningswing;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mirai
 */
public class Bai2 extends javax.swing.JFrame {

	/**
	 * Creates new form Bai2
	 */
	public Bai2() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialise the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		num1 = new javax.swing.JButton();
		num2 = new javax.swing.JButton();
		num3 = new javax.swing.JButton();
		num4 = new javax.swing.JButton();
		num5 = new javax.swing.JButton();
		num6 = new javax.swing.JButton();
		num7 = new javax.swing.JButton();
		num8 = new javax.swing.JButton();
		num9 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Button Swap");

		num1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num1.setText("1");
		num1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num1ActionPerformed(evt);
			}
		});

		num2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num2.setText("2");
		num2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num2ActionPerformed(evt);
			}
		});

		num3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num3.setText("3");
		num3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num3ActionPerformed(evt);
			}
		});

		num4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num4.setText("4");
		num4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num4ActionPerformed(evt);
			}
		});

		num5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num5.setText("5");
		num5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num5ActionPerformed(evt);
			}
		});

		num6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num6.setText("6");
		num6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num6ActionPerformed(evt);
			}
		});

		num7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num7.setText("7");
		num7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num7ActionPerformed(evt);
			}
		});

		num8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num8.setText("8");
		num8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num8ActionPerformed(evt);
			}
		});

		num9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		num9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				num9ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(51, 51, 51)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(layout.createSequentialGroup()
										.addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(59, 59, 59).addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE,
												83, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(56, 56, 56).addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE,
												86, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										layout.createSequentialGroup()
												.addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(num9, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 86,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(num6, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 86,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(60, 60, 60)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(58, 58, 58)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(75, 75, 75)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(75, 75, 75)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(58, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void num1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num1ActionPerformed

	}// GEN-LAST:event_num1ActionPerformed

	private void num2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num2ActionPerformed

	}// GEN-LAST:event_num2ActionPerformed

	private void num3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num3ActionPerformed

	}// GEN-LAST:event_num3ActionPerformed

	private void num4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num4ActionPerformed

	}// GEN-LAST:event_num4ActionPerformed

	private void num5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num5ActionPerformed

	}// GEN-LAST:event_num5ActionPerformed

	private void num6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num6ActionPerformed

	}// GEN-LAST:event_num6ActionPerformed

	private void num7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num7ActionPerformed

	}// GEN-LAST:event_num7ActionPerformed

	private void num8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num8ActionPerformed
		if (num9.getText() == "") {
			String b = num9.getText();
			num9.setText(num8.getText());
			num8.setText(b);
		} else if (num7.getText() == "") {
			String b = num7.getText();
			num7.setText(num8.getText());
			num8.setText(b);
		} else if (num5.getText() == "") {
			String b = num5.getText();
			num5.setText(num8.getText());
			num8.setText(b);
		}
	}// GEN-LAST:event_num8ActionPerformed

	private void num9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num9ActionPerformed
		if (rootPaneCheckingEnabled) {
			
		} else {
			
		}
	}// GEN-LAST:event_num9ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Bai2().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton num1;
	private javax.swing.JButton num2;
	private javax.swing.JButton num3;
	private javax.swing.JButton num4;
	private javax.swing.JButton num5;
	private javax.swing.JButton num6;
	private javax.swing.JButton num7;
	private javax.swing.JButton num8;
	private javax.swing.JButton num9;
	// End of variables declaration//GEN-END:variables
}
